### PR TITLE
Amphenol: Added SMA 132289 connector

### PR DESCRIPTION
**Pull request by myfreescalewebpage**

### CODE REVIEW

**Comment by pointhi** [comment]
please fix KLC:

```
checking module: Amphenol_RF_SMA_132289
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

Furthermore:
- Silk screen shouldn't be above pads. You could use F.Fab or Dwgs.User for drawings
- as doc you could simply but a datasheet url

You could use https://github.com/KiCad/kicad-library-utils to do basic KLC checks (but this check doesn't include the whole KLC!)

**Comment by myfreescalewebpage** [comment]
Sorry, realized reading your comment that I have not pushed the right version with KLC violation rules fixed. Now done, sorry for inconvenience.

Also added the doc and fixed the silk screen layer replaced to Dwgs.User.

**Comment by pointhi** [comment]
- For Connectors the courtjard Line has to have a distance of 0,5mm from pads and parts of the connector
- Paste and mask is wrong for the bottom pads. I would suggest to remove paste, because you wouldn't normally solder this connector in the reflow oven
- I would suggest to fix numeration:
  - pad 1: RF
  - pad 2: GND (pad 2, 3, 4, 5 should be pad 2)

**Comment by myfreescalewebpage** [comment]
Thanks for the review.
Done.

**Comment by pointhi** [comment]
I looked onto the datasheet (http://www.amphenolrf.com/downloads/dl/file/id/2775/product/2917/132289_customer_drawing.pdf) and it seems like your pad sizes, positions, drawings,... are differ from it.

**Comment by myfreescalewebpage** [comment]
@pointhi Yes they are larger so it is stronger. Also easier to solder by hand.

**Comment by jkriege2** [comment]
Then maybe add 2 footprint? One with standard and one `..._HandSoldering` with larger pads?

cu
JAN

**Comment by evanshultz** [comment]
@myfreescalewebpage Will you be able to review the comments above and finish this PR soon?

**Comment by myfreescalewebpage** [comment]
@evanshultz now done, sorry no time to do it before. let me known if something else to fix. klc is ok.

**Pull request merged**
