### PR TITLE
Amphenol T821 series 6 pin box header pitch 2.54mm

### PR DESCRIPTION
**Pull request by tk5ep**
Amphenol T821 series 6 pin box header pitch 2.54mm

### CODE REVIEW

**Comment by fauxpark** [comment]
Just FYI, we already have generic IDC (box) headers over at [KiCad/Connectors_IDC.pretty](https://github.com/KiCad/Connectors_IDC.pretty). They come in multiple polarities with straight and angled orientations. The difference in dimensions between manufacturers, if any, is likely to be negligible as the form factor is a defacto standard.

**Comment by tk5ep** [comment]
@fauxpark 
Thanks for the info. I overlooked that ...

Librairies handling is really a mess with Kicad ! One never knows what exists and how to find them...

Thanks,

**Comment by fauxpark** [comment]
No worries, the repo is fairly new so I'm not sure if it appears in the latest stable download. The libraries are indeed in dire need of cleaning up but the good news is it's already in progress. The librarians are working as hard as they have time for to whip it into shape, and any contributions from us users brightens their day, I'm sure :)

**Comment by tk5ep** [comment]
You're right !

Btw, do you know if a 3d shape exists for these kind of connectors : 
http://www.mouser.com/ds/2/670/sds-xxj-535158.pdf

**Comment by tk5ep** [comment]
Oops !
I found it on the manufacturer site and have imported it in Kicad.
Now, where to put it ? (part of the mess)

**Comment by poeschlr** [comment]
@tk5ep we are archiving this repo because we are preparing for the v5 release.
Might i suggest asking about the 3d models over at the packages-3d repo?
(If you designed them your self and we don't already have script generated models yours might be a good addition. If you downloaded the 3d models from a third party, we sadly can not use them.)

**Pull request closed without merging**
