### PR TITLE
added ECU connector

### PR DESCRIPTION
**Pull request by seec**

### CODE REVIEW

**Review by pointhi — CHANGES_REQUESTED** [review]
Please fix KLC:

```
checking module: Connectors_Amphenol_FCI:HCCPHPE24BKA90
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

**Comment by evanshultz** [comment]
@seec Will you be able to review the comments above and finish this PR soon?

**Comment by seec** [comment]
what PR mean? (sorry im not a native english)

**Comment by evanshultz** [comment]
@seec Thanks for responding, and no need to apologize. PR means pull request. It's this process, where you make changes and request (ask) us to pull (merge) them. What I'm asking is if you can fix the issues above so this ECU connector can be added to KiCad.

**Comment by seec** [comment]
thanks I got it. I'm going to fix it.
just was a little bit busy

**Comment by SchrodingersGat** [comment]
@seec let us know when you make the fixes for this pull request :)

**Comment by poeschlr** [comment]
@seec if you are still interested in contributing please re commit your changes to the new [kicad-footprints repo](https://github.com/KiCad/kicad-footprints). This repo will be archived because we transfer the footprints contained herein to the new repo in preparation for the v5 release. (No new pull request will be accepted here.)

**Pull request closed without merging**
