### PR TITLE
SMA-1321134

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jeromebeguin** [comment]
Could you check and merged ?

**Comment by jkriege2** [comment]
Hi!

nice work!!!

Please fix these two small errors, then I can merge:
```
Checking footprint 'Amphenol_SMA_132134':
  Violating Rule 10.4
    3D model reference
    Model path should start with '${KISYS3DMOD}/'
    3D model name is different from footprint name (found 'Amphenol_SMA_1321134', should be 'Amphenol_SMA_132134')
```

Best,
JAN

**Comment by poeschlr** [comment]
Again sorry for the long delay.

The courtyard clearance measured to the copper ring of the pads should be 0.25mm 
Currently you have 0.21mm

This connector is missing a reference to the datasheet in the documentation field as well.

For connectors it should be 0.5 but i think this is such that you can easily plug it in/out. You have 0.5mm with respect to the connector body which should be alright if i understand the KLC correctly. (@SchrodingersGat or @jkriege2 am i correct with this interpretation?).

**Comment by evanshultz** [comment]
@jeromebeguin Will you be able to review the comments above and finish this PR soon?

**Pull request closed without merging**
